### ISSUE TITLE
I would love to use this player but am to stupid to install on windows 10

### ISSUE THREAD

**Issue by Nedks** [kanishka-linux/kawaii-player#13]
Could anyone make a video on how to do it?

**Comment by kanishka-linux** [comment]
here is [link to 7z](https://github.com/kanishka-linux/kawaii-player/releases/download/v2.8.0-0/kawaii-player-2.8.0-0.windows10.x86_64-bin.7z) archive. Just click on the link and download it.

Then extract downloaded archive. For extracting you can use [this software](http://www.7-zip.org/a/7z1701-x64.exe).

Now go to extracted folder and click on **kawaii_player** executable. 

There is no need to call oneself stupid. I myself have very little knowledge of windows system. If you are facing specific problem then atleast enumerate the steps you've taken to install it, so that we can pin point the problem.

**Comment by Nedks** [comment]
Thank you
