### ISSUE TITLE
Updated install instructions for Debian/Ubuntu

### ISSUE THREAD

**Issue by tidux** [kanishka-linux/kawaii-player#14]
Rather than instructing people to use `gdebi` or another graphical front end, use `apt-get -f install` to install missing dependencies, like so:

`dpkg -i kawaii-player.deb && apt-get -f install`

This is why the -f flag to apt-get install exists.

**Comment by kanishka-linux** [comment]
using **'apt-get -f'** in order to install missing dependencies sometimes may break the system. It is pretty risky to use. I personally will not recommend anyone to do it on any debian based system. I think one should use it as a last resort. Installing package along with its dependencies is the best way to ensure long term stability of system, that's why I recommended use of gdebi.

**Comment by clemencyworld1** [comment]
"sudo apt install /path/to/Deb" will still resolve the dependencies
