### ISSUE TITLE
Integrate plugins/features to mpv

### ISSUE THREAD

**Issue by togoti3150** [kanishka-linux/kawaii-player#27]
I want to integrate most of these to original mpv so i can control some other features.. any way to do that?

**Comment by kanishka-linux** [comment]
I think, it should be possible, if one uses mpv binary with kawaii-player. One has to keep plugins in regular mpv config directory, and with mpv binary as playback engine, atleast some plugins feature may work.

**Comment by togoti3150** [comment]
so do i have to compile it or something or just figure around the file name systems and folder dirs stuff?

**Comment by kanishka-linux** [comment]
I think, I understood it differently earlier. I guess, you want to use features of kawaii-player like library management etc.. but want to open videos is original mpv player, right? If that is the case, then it is possible. 

Once you've kawaii-player installed, edit `~/.config/kawaii-player/config.txt`, and update MPV as default player i.e. `DefaultPlayer=MPV` (all capital letters for MPV).

Then, restart player, and you'll be able to use kawaii-player as library manager, but it will open videos in external mpv window.
Not all features may work, but some of them will. You can try it out.

**Comment by Aurareus** [comment]
Sorry to piggyback off this issue, but I think I have essentially the same query/request.
I would like to use mpv but I would like to use it with a full-featured GUI with library/playlist management and such.
Until now I've been using MPC-QT to achieve this and it's perfect for my needs.
But I now wish to use some [lua scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) and Vapoursynth filters (like [SVP](https://www.svp-team.com/)) and as far as I can see that isn't possible with MPC-QT so I've been looking for an alternative front-end for mpv and this looks like the best options from what I've seen.

Is this possible with Kawaii Player using the method you mention?
Having media open in an external mpv window isn't ideal but if there is no alternative I'd settle for that.

**Comment by kanishka-linux** [comment]
once one uses `DefaultPlayer=MPV or mpv` - one can get essentially all features of mpv. Since it uses mpv binary available on your system as it is. Place all scripts inside `~/.config/mpv/scripts/` and add keybindings and other configs using kawaii-player GUI. `More->Preferences->Config/Shortcuts`. Most scripts and mpv settings will work as it is. 

I just tried [crop](https://github.com/occivink/mpv-scripts#croplua) lua script and it worked without any problem.

Only issue is `MPV/mpv` uses slave mode which is completely removed by mpv team. So it won't work with latest mpv build most probably. 

mpv available on many linux distro still has slave mode available, so it may work in such cases, you can check that out.

When using `DefaultPlayer=libmpv` - external lua scripts/plugins won't be loaded. libmpv provides only api to interact with player, so lua scripts/plugins which interact with mpv ui simply won't work, since ui components of kawaii-player are different.

**Comment by Aurareus** [comment]
That's great, thanks a lot for the help and for the work you've put into Kawaii-Player!

**Comment by kanishka-linux** [comment]
In between added support for mpv input-ipc-server as a replacement to slave mode. 
Instructions are available in the [README](https://github.com/kanishka-linux/kawaii-player#mpv-input-ipc-server). 
So latest build of mpv binary can also work with kawaii-player now.
