### ISSUE TITLE
Support for the Universal Playlist Format?

### ISSUE THREAD

**Issue by skorokithakis** [kanishka-linux/kawaii-player#3]
I just found out about this player, good work! I like many of your ideas, especially about having a playlist you can access from anywhere, which is something I've been working on too. I wanted to show you what I developed just to see if you'd have any interest in supporting it. It's a playlist format that's designed to be portable across computers and even across services, without needing to move the actual files.

The spec is here, right now it's geared towards audio, but there's no reason why it can't be used for video as well:

http://universalplaylist.stavros.io/

Thanks!

**Comment by kanishka-linux** [comment]
Playlist format designed by you looks good and interesting. In order to make it more detailed, I think you need to include file format along with codec information. In case of video playlist, I think it should include external subtitle/captions file path to make it more complete.

To be frank, currently it's somewhat cumbersome to add support for completely new playlist format, which I have not taken into account while designing the programme.

I think you should approach vlc/mpv or other major media players in the market. Because without proper backing of major players it's difficult for any standard to get wider acceptance, and the issue of playlist format is basically the issue of common standard, for which there is no common agreement.

**Comment by skorokithakis** [comment]
That's true, thank you. Why do you think the file format needs to be included? Isn't that a feature of the file itself?

**Comment by kanishka-linux** [comment]
If file is some arbitrary http url, similar to you youtube final file url, then it's easier for player to identify the content easily.
