### ISSUE TITLE
minor bit in readme

### ISSUE THREAD

**Issue by mc4man** [kanishka-linux/kawaii-player#9]
The 1st & easiest choice for ubuntu 16.04 and newer & some debian would be to just install with apt as it resolves dependencies . (- apt, not apt-get.

**Comment by kanishka-linux** [comment]
In fact both apt and apt-get resolve dependencies and install packages properly. I have started using Ubuntu again since last few months, and now it seems 'apt' is much better choice. Earlier everyone used to use apt-get. But I guess both are fine and do their job properly. However, I'll update the readme as per latest trend. Thanks!
